import React, { useState, useEffect } from 'react';
import { UserProfile } from '../../types';
import { StorageService } from '../../services/storageService';
import { toast } from 'sonner';
import { CalendarValidationService } from '../../services/calendarValidationService';

interface PlanSessionModalProps {
  isOpen: boolean;
  onClose: () => void;
  selectedDate: Date | null;
  clients: UserProfile[];
  onUpdate: (clients: UserProfile[]) => void;
}

export const PlanSessionModal: React.FC<PlanSessionModalProps> = ({
  isOpen,
  onClose,
  selectedDate,
  clients,
  onUpdate
}) => {
  const [selectedClientId, setSelectedClientId] = useState<string>('');
  const [notes, setNotes] = useState('');
  const [autoGenerate, setAutoGenerate] = useState(false);
  const [validationResult, setValidationResult] = useState<{
    canPlan: boolean;
    severity: 'error' | 'warning' | 'info' | 'success';
    message?: string;
    details?: string[];
    canForce?: boolean;
  } | null>(null);
  const [forcePlan, setForcePlan] = useState(false);

  useEffect(() => {
    if (isOpen && selectedDate) {
      setSelectedClientId('');
      setNotes('');
      setAutoGenerate(false);
      setValidationResult(null);
      setForcePlan(false);
    }
  }, [isOpen, selectedDate]);

  // Valider la planification quand le client ou la date change
  useEffect(() => {
    if (selectedClientId && selectedDate) {
      const client = clients.find(c => c.id === selectedClientId);
      if (client) {
        const validation = CalendarValidationService.validateSessionPlanning(client, selectedDate);
        setValidationResult(validation);
        setForcePlan(false);
      }
    } else {
      setValidationResult(null);
    }
  }, [selectedClientId, selectedDate, clients]);

  if (!isOpen || !selectedDate) return null;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!selectedClientId) {
      toast.warning('Veuillez sélectionner un client');
      return;
    }

    const client = clients.find(c => c.id === selectedClientId);
    if (!client) return;

    // Utiliser la validation complète
    const validation = validationResult || 
      CalendarValidationService.validateSessionPlanning(client, selectedDate);

    // Si erreur bloquante et pas de forçage, arrêter
    if (!validation.canPlan && !forcePlan) {
      toast.error(validation.message || 'Impossible de planifier cette session', {
        description: validation.details?.join(' ')
      });
      return;
    }

    // Si avertissement et pas de forçage, demander confirmation
    if (validation.severity === 'warning' && !forcePlan) {
      toast.warning(validation.message || 'Attention', {
        description: validation.details?.join(' '),
        action: {
          label: 'Planifier quand même',
          onClick: () => {
            setForcePlan(true);
            // Relancer la soumission après un court délai
            setTimeout(() => {
              const form = e.target as HTMLFormElement;
              form.requestSubmit();
            }, 100);
          }
        },
        cancel: {
          label: 'Annuler'
        },
        duration: 5000
      });
      return;
    }

    const sessionId = `planned_${Date.now()}`;
    const newPlannedSession = {
      id: sessionId,
      date: selectedDate.toISOString(),
      clientId: selectedClientId,
      notes: notes.trim() || undefined,
      isAutoGenerated: false
    };

    let generatedSessions: any[] = [];
    const updatedClient: UserProfile = {
      ...client,
      plannedSessions: [...(client.plannedSessions || []), newPlannedSession]
    };

    // Si auto-generate est activé, générer toutes les sessions futures basées sur le programme
    if (autoGenerate && client.activeProgram) {
      const program = client.activeProgram;
      generatedSessions = generateSessionsFromProgram(client, selectedDate, program);
      updatedClient.plannedSessions = [
        ...(client.plannedSessions || []),
        newPlannedSession,
        ...generatedSessions
      ];
    }

    const updatedClients = StorageService.updateClient(updatedClient);
    StorageService.saveClients(updatedClients);
    onUpdate(updatedClients);
    
    const message = autoGenerate 
      ? `Session planifiée et ${generatedSessions.length} sessions générées automatiquement (24 semaines)`
      : 'Session planifiée avec succès';
    
    // Afficher un toast selon la sévérité
    if (validation.severity === 'warning' && forcePlan) {
      toast.warning(message, {
        description: 'Session planifiée malgré les avertissements'
      });
    } else if (validation.severity === 'info') {
      toast.info(message);
    } else {
      toast.success(message);
    }
    
    onClose();
  };

  const generateSessionsFromProgram = (client: UserProfile, startDate: Date, program: any) => {
    const sessions: any[] = [];
    const sessionsPerWeek = program.sessionsPerWeek;
    // Utiliser 24 semaines par défaut si la durée n'est pas définie
    const duration = program.duration || 24;
    const totalSessions = duration * sessionsPerWeek;

    // Calculer les jours de la semaine pour les sessions (ex: lundi, mercredi, vendredi)
    const sessionDays = getSessionDays(sessionsPerWeek);
    
    // Trouver le premier jour de session de la semaine à partir de la date de départ
    let currentDate = new Date(startDate);
    const startDayOfWeek = currentDate.getDay();
    
    // Trouver le prochain jour de session valide
    let daysToAdd = 0;
    while (!sessionDays.includes((startDayOfWeek + daysToAdd) % 7) && daysToAdd < 7) {
      daysToAdd++;
    }
    if (daysToAdd > 0) {
      currentDate = new Date(currentDate.getTime() + daysToAdd * 24 * 60 * 60 * 1000);
    }
    
    let sessionCount = 0;
    // 24 semaines par défaut
    const endDate = new Date(startDate.getTime() + duration * 7 * 24 * 60 * 60 * 1000);

    while (sessionCount < totalSessions && currentDate <= endDate) {
      const dayOfWeek = currentDate.getDay();
      
      if (sessionDays.includes(dayOfWeek)) {
        // Utiliser le service de validation pour vérifier les conflits
        const validation = CalendarValidationService.canPlanSessionOnDate(client, currentDate);
        
        if (validation.canPlan) {
          sessions.push({
            id: `planned_auto_${Date.now()}_${sessionCount}`,
            date: new Date(currentDate).toISOString(),
            clientId: client.id,
            isAutoGenerated: true
          });
          sessionCount++;
        }
      }

      // Passer au jour suivant
      currentDate = new Date(currentDate.getTime() + 24 * 60 * 60 * 1000);
    }

    return sessions;
  };

  const getSessionDays = (sessionsPerWeek: number): number[] => {
    // Retourne les jours de la semaine (0=dimanche, 1=lundi, etc.)
    switch (sessionsPerWeek) {
      case 2:
        return [1, 4]; // Lundi, Jeudi
      case 3:
        return [1, 3, 5]; // Lundi, Mercredi, Vendredi
      case 4:
        return [1, 2, 4, 5]; // Lundi, Mardi, Jeudi, Vendredi
      case 5:
        return [1, 2, 3, 4, 5]; // Lundi à Vendredi
      case 6:
        return [1, 2, 3, 4, 5, 6]; // Lundi à Samedi
      default:
        return [1, 3, 5]; // Par défaut: 3 fois par semaine
    }
  };

  const dateString = selectedDate.toLocaleDateString('fr-FR', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  return (
    <div className="fixed inset-0 z-[1000] bg-black/80 flex items-center justify-center backdrop-blur-xl" onClick={onClose}>
      <div
        className="bg-gradient-to-br from-gray-900/95 to-black/95 border border-[var(--primary-teal)]/30 rounded-2xl w-full max-w-md p-6 space-y-5 shadow-2xl shadow-[var(--primary-teal)]/10"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header - Design épuré */}
        <div className="flex items-center justify-between pb-3 border-b border-gray-800/50">
          <div>
            <h2 className="font-bebas text-xl text-white tracking-wider">Planifier une Session</h2>
            <p className="text-[9px] font-mono text-gray-500 mt-1">{dateString}</p>
          </div>
          <button
            onClick={onClose}
            className="w-8 h-8 flex items-center justify-center text-gray-400 hover:text-white hover:bg-white/5 rounded-lg transition-all"
          >
            ✕
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="space-y-4">
          {/* Sélection du client */}
          <div>
            <label className="text-[9px] font-mono text-gray-500 uppercase mb-1.5 block tracking-wider">Client</label>
            <select
              value={selectedClientId}
              onChange={(e) => setSelectedClientId(e.target.value)}
              className="w-full bg-black/40 border border-gray-800/50 rounded-lg px-3 py-2.5 text-sm text-white font-mono focus:border-[var(--primary-teal)]/50 focus:outline-none focus:ring-1 focus:ring-[var(--primary-teal)]/20 transition-all"
              required
            >
              <option value="">Sélectionner un client</option>
              {clients.map(client => (
                <option key={client.id} value={client.id}>
                  {client.nom} {client.activeProgram ? `(${client.activeProgram.sessionsPerWeek}x/semaine)` : ''}
                </option>
              ))}
            </select>
          </div>

          {/* Auto-génération basée sur le programme */}
          {selectedClientId && clients.find(c => c.id === selectedClientId)?.activeProgram && (
            <div className="flex items-start gap-3 p-3 bg-[var(--primary-teal)]/10 border border-[var(--primary-teal)]/20 rounded-lg">
              <input
                type="checkbox"
                id="autoGenerate"
                checked={autoGenerate}
                onChange={(e) => setAutoGenerate(e.target.checked)}
                className="w-4 h-4 accent-[var(--primary-teal)] mt-0.5"
              />
              <label htmlFor="autoGenerate" className="text-xs font-mono text-gray-300 cursor-pointer flex-1">
                Générer automatiquement toutes les sessions du programme
                <span className="block text-[9px] text-gray-500 mt-1">
                  ({clients.find(c => c.id === selectedClientId)?.activeProgram?.sessionsPerWeek}x/semaine pendant{' '}
                  {clients.find(c => c.id === selectedClientId)?.activeProgram?.duration || 24} semaines)
                </span>
                <span className="block text-[9px] text-[var(--primary-teal)] mt-1">
                  ⚠️ Une seule session par jour maximum par client
                </span>
              </label>
            </div>
          )}

          {/* Affichage de la validation */}
          {validationResult && selectedClientId && (
            <div className={`p-3 rounded-lg border ${
              validationResult.severity === 'error' 
                ? 'bg-red-500/10 border-red-500/30 text-red-400'
                : validationResult.severity === 'warning'
                ? 'bg-orange-500/10 border-orange-500/30 text-orange-400'
                : validationResult.severity === 'info'
                ? 'bg-blue-500/10 border-blue-500/30 text-blue-400'
                : 'bg-green-500/10 border-green-500/30 text-green-400'
            }`}>
              <div className="flex items-start gap-2">
                <span className="text-lg">
                  {validationResult.severity === 'error' ? '🚫' :
                   validationResult.severity === 'warning' ? '⚠️' :
                   validationResult.severity === 'info' ? 'ℹ️' : '✅'}
                </span>
                <div className="flex-1">
                  <p className="text-xs font-semibold mb-1">
                    {validationResult.message || 'Validation OK'}
                  </p>
                  {validationResult.details && validationResult.details.length > 0 && (
                    <ul className="text-[10px] space-y-1 opacity-90">
                      {validationResult.details.map((detail, idx) => (
                        <li key={idx}>• {detail}</li>
                      ))}
                    </ul>
                  )}
                  {validationResult.severity === 'warning' && validationResult.canForce && (
                    <p className="text-[10px] mt-2 opacity-75">
                      Vous pouvez planifier quand même en cliquant sur "Planifier"
                    </p>
                  )}
                </div>
              </div>
            </div>
          )}

          {/* Notes */}
          <div>
            <label className="text-[9px] font-mono text-gray-500 uppercase mb-1.5 block tracking-wider">Notes (optionnel)</label>
            <textarea
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              className="w-full bg-black/40 border border-gray-800/50 rounded-lg px-3 py-2.5 text-sm text-white font-mono placeholder:text-gray-600 focus:border-[var(--primary-teal)]/50 focus:outline-none focus:ring-1 focus:ring-[var(--primary-teal)]/20 transition-all resize-none h-20"
              placeholder="Notes pour cette session..."
            />
          </div>

          {/* Footer - Design discret */}
          <div className="flex justify-end gap-2 pt-4 border-t border-gray-800/50">
            <button
              type="button"
              onClick={onClose}
              className="px-5 py-2 bg-white/5 text-gray-400 rounded-lg text-xs font-mono uppercase hover:bg-white/10 hover:text-white transition-all border border-gray-800/50"
            >
              Annuler
            </button>
            <button
              type="submit"
              disabled={validationResult?.severity === 'error' && !forcePlan}
              className={`px-5 py-2 rounded-lg text-xs font-mono uppercase transition-all border ${
                validationResult?.severity === 'error' && !forcePlan
                  ? 'bg-gray-800/50 text-gray-600 border-gray-800/50 cursor-not-allowed'
                  : validationResult?.severity === 'warning' && !forcePlan
                  ? 'bg-orange-500/20 text-orange-400 border-orange-500/30 hover:bg-orange-500/30'
                  : 'bg-[var(--primary-teal)]/20 text-[var(--primary-teal)] border-[var(--primary-teal)]/30 hover:bg-[var(--primary-teal)]/30'
              }`}
            >
              {validationResult?.severity === 'warning' && !forcePlan 
                ? 'Planifier quand même' 
                : 'Planifier'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

